### ISSUE TITLE
Failed connecting to the database using Docker compose

### ISSUE THREAD

**Issue by Meeshoo** [kpeiruza/docker-hashtopolis-server#1]
I am trying to get this up and running with docker compose, here is my docker-compose.yml

```
version: '3'

services:

  hash_mysql:
    container_name: hash_mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: verySecret

  hastopolis:
    container_name: hashtopolis
    image: kpeiruza/hashtopolis
    environment:
      H8_USER: root
      H8_PASS: verySecret
      H8_EMAIL: root@localhost
    links:
      - hash_mysql:mysql
    ports:
     - "80:80"
```
 I am getting the error:

`Failed connecting to the database.... Sleeping 5s and retrying 11 more.`

I thought this might be an issue with my compose setup (which it still may be) but I have tried running with the basic setup listed in the readme:

`docker run --name mydb -e MYSQL_ROOT_PASSWORD=PleaseChangeMe -d mysql:5.7`
`docker run --link mydb:mysql -d -p 80:80 kpeiruza/hashtopolis`

and I get the same error.

Is this an issue with my setup?
